#Busca simples por um restaurante utiliando page-object

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "capybara"
gem "cucumber"
gem "chromedriver-helper", '1.1.0'
gem "selenium-webdriver"
